config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'login' => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: %i[get delete]

  constraints provider: /#{OmniAuth.registered_providers.join('|')}/ do
    get 'login/with/:provider' => 'sessions#oauth', as: :oauth_login
    match 'auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  end

  resources :productions, only: %i[index]
  resources :reviews, only: %i[new create] do
    post :submit, on: :member
  end
  resources :submissions, only: %i[index show update] do
    match :moderate, on: :member, via: %i[patch put]
  end

  root to: 'reviews#index'
end

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  = content_tag :div, class: class_string('flash', "flash--#{type}") do
    = message.html_safe

app/views/shared/_navigation.html.haml
.navigation
  = link_to root_path, class: 'navigation__link navigation__logo' do
    = inline_svg 'logo'
    %span= t('application.name')

  - if logged_in?
    .navigation__user{'data-controller': 'user-menu'}
      = link_to '#', class: 'navigation__link', data: { target: 'user-menu.link' } do
        = inline_svg('icons/user')
        %span= current_user
      .navigation__menu{'data-target': 'user-menu.menu'}
        - if can? :read, Submission
          = link_to submissions_path, class: 'navigation__item' do
            = inline_svg('icons/submission', class: 'navigation__icon')
            .navigation__text= t('.submissions')
            = badge(Submission.pending.count)
        = link_to logout_path, method: :delete, class: 'navigation__item' do
          = inline_svg('icons/log_out', class: 'navigation__icon')
          .navigation__text= t('.log_out')
  - else
    = authenticated_link_to login_path, class: 'navigation__link login-link' do
      = inline_svg('icons/user')
      = t('.log_in')