config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'login' => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout, via: %i[get delete]

  constraints provider: /#{OmniAuth.registered_providers.join('|')}/ do
    get 'login/with/:provider' => 'sessions#oauth', as: :oauth_login
    match 'auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  end

  resources :productions, only: %i[index]
  resources :reviews, only: %i[new create] do
    post :submit, on: :member
  end
  resources :submissions, only: %i[index show update] do
    match :moderate, on: :member, via: %i[patch put]
  end

  root to: 'reviews#index'
end

app/models/submission.rb
# frozen_string_literal: true

class Submission < ApplicationRecord
  include Hashable

  belongs_to :review
  belongs_to :moderator, class_name: 'User', optional: true
  has_one :reviewer, through: :review
  has_one :production, through: :review

  enum state: {
    pending: 'pending',
    changes_requested: 'changes_requested',
    approved: 'approved',
    rejected: 'rejected'
  }

  validates :review, :version_number, presence: true
  validates :feedback, presence: true, unless: :pending?

  def version_number
    super || (self.version_number = review.version_number)
  end
end

app/controllers/submissions_controller.rb
# frozen_string_literal: true

class SubmissionsController < ApplicationController
  require_login

  def index
    authorize! :read, Submission
  end

  def show
    authorize! :read, submission
  end

  def update
    authorize! :update, submission
    update_review
    redirect_to submission
  end

  def moderate
    authorize! :update, submission
    ModerateSubmission
      .new(submission, current_user, moderation_params)
      .on(:success) { moderation_success }
      .on(:failure) { moderation_failure }
      .call
  end

  private

  def moderation_params
    return {} unless params[:submission].present?
    @moderation_params ||= params.require(:submission)
  end

  def review_params
    @review_params ||= moderation_params[:review] || {}
  end

  def moderation_success
    submission.reload
    redirect_to submissions_path, alert: t(".#{submission.state}")
  end

  def moderation_failure
    render :show
  end

  def submissions
    @submissions ||= Submissions.new(params)
  end

  def submission
    @submission ||= Submission.find(params[:id])
  end

  def review_form
    @review_form ||= ReviewForm.new(submission.review, review_params)
  end

  def update_review
    review_form.update(review_params) if review_params.present?
  end

  helper_method :submission, :submissions, :review_form
end

app/views/submissions/_moderation_pending.html.haml
- if can?(:moderate, submission)
  = form_for submission, url: moderate_submission_path(submission), html: { class: 'moderation__feedback' } do |form|
    = form.label :feedback, class: 'form__label form__label--required' do
      = t('.feedback')
    = form.text_area :feedback
    - form.object.errors.full_messages_for(:feedback).each do |message|
      %p.form__error= message

    .form__buttons.moderation__buttons
      = button class: 'moderation__reject', text: t('.reject'), icon: 'reject', name: 'submission[state]', value: 'rejected'
      = button class: 'moderation__change', text: t('.change'), icon: 'change', name: 'submission[state]', value: 'changes_requested'
      = button class: 'moderation__approve', text: t('.approve'), icon: 'approve', name: 'submission[state]', value: 'approved'

- else
  .moderation__feedback
    .form__label= m t('.cannot_self_moderate')

app/views/submissions/_submission.html.haml
= link_to submission, class: class_string('submission', "submission--#{submission.state}") do
  .submission__info
    .submission__production= submission.review.production.name
    .submission__review
      %span.submission__reviewer= submission.review.reviewer.name
      %span.submission__time= t('.ago', age: time_ago_in_words(submission.created_at))

app/views/submissions/index.html.haml
.submissions
  %header.page-title
    %h1.title= t('.title')
  .tabs.submissions__tabs{role: 'tablist'}
    - Submission.states.values.each do |state|
      = link_to submissions_path(submissions.parameters.except(:page).merge(state: state)), role: 'tab', class: class_string('tab', 'submissions__tab', 'tab--active' => submissions.parameters[:state] == state) do
        = badge(Submission.where(state: state).count)
        %span.tab__text= t(state, scope: 'submissions.index.tabs')
  = render partial: 'submission', collection: submissions

app/views/submissions/show.html.haml
.moderation__review
  .breadcrumbs
    = link_to t('submissions.index.title'), submissions_path

  = form_for submission, html: { class: 'moderation__production inline__form', data: { controller: 'review-production' } } do |form|
    = form.fields_for :review, submission.review do |review|
      = review.fields_for :production, submission.production do |production|
        .moderation__title
          = production.label :name, t('.review_of', name: submission.reviewer), class: 'inline-label'
          = production.text_field :name, class: 'text-field moderation__production-name', autocomplete: 'off', data: { target: 'review-production.name', action: 'input->review-production#nameChanged keydown->review-production#keyDown' }
          = production.hidden_field :id, data: { target: 'review-production.id' }
          = production.label :performance_date, t('.on_date'), class: 'inline-label'
          = review.date_field :performance_date, class: 'text-field date-field moderation__performance-date'
          = button text: t('.save_changes'), disabled: true, class: 'moderation__save', data: { target: 'review-production.next' }

        .moderation__production-autocomplete.hidden{data: { target: 'review-production.autocomplete' }}
          %ul.moderation__productions{data: { target: 'review-production.productions', action: 'click->review-production#productionClicked' }}

  .moderation__preview= m submission.review.text

= render "moderation_#{submission.state}"